Add page for creating an event plan to web2
CSUN-COMP-490-Team-KBBQ/wya pull request #26
Opened 2022-04-29 03:33 UTC by jesc0bar

2022-04-29 03:49 UTC, mtahery20 commented
Looks good! Functionality is working too (invited myself to an event)

2022-04-29 03:50 UTC, mtahery20 submitted a review, later dismissed

2022-04-29 23:25 UTC, navarrojandg commented
Looks good to me.

@ivancuadra869 Just wanted to note here that Jorge has started to bring in the `web/src/modules` folder into `web2`

2022-04-29 23:27 UTC, navarrojandg submitted a review, later dismissed

2022-05-03 07:07 UTC, ivancuadra869 commented on apps/web2/src/pages/PlanAnEventPage/PlanAnEventPage.tsx
> +                Event Settings
Not sure if you meant to change this, but it seems like it should be something else.

2022-05-03 07:08 UTC, ivancuadra869 requested changes
Looks great and the functionality also works.

2022-05-04 17:34 UTC, merged