Implement Form Validation
CSUN-COMP-490-Team-KBBQ/wya pull request #35
Opened 2022-05-05 04:30 UTC by mtahery20

Added form validation with functionality to the following items:
-If user signs in with incorrect password or email address
-After user sends a password reset link, a success notification is shown

I also added a link to return back to the login page from the password reset page

2022-05-05 04:46 UTC, ssarma107 requested changes
everything is working except for the registration page, still needs form validation but approving for the log-in page and reset password page.

2022-05-05 22:38 UTC, navarrojandg commented on apps/web2/src/pages/FriendsPage/FriendsPage.tsx
> +                    type="text"
Believe that `type="email"` is correct here.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

2022-05-05 22:44 UTC, navarrojandg commented on apps/web2/src/pages/FriendsPage/FriendsPage.tsx
> +                    type="text"
Making it `type="text"` allows us to accept any string input and rely on the regex test to validate the string as an email. Helps make errors uniform.

-- Marmar

2022-05-06 00:04 UTC, ivancuadra869 commented
The validation that is present works. There could be validation added, I'm going to approve this and merge. If you there is time, we'll take a look at the remaining validation

2022-05-06 00:04 UTC, merged